apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    openshift.io/display-name: "OpenShift Pipelines"
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: latest
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace