---

- name: Run Bitwarden PW manager tasks
  include_tasks:
    file: bitwarden_auth
  tags:
    - bitwarden

- name: Deploy the TF resources
  community.general.terraform:
    project_path: "{{ tf_project_path }}"
    state: absent
    variables_files:
      - "{{ tf_project_path }}/main.tfvars"
    variables:
      token: "{{ terraform_token }}"
      admin_password: "{{ admin_password }}"
      developer_password: "{{ developer_password }}"
  tags:
    - always