---

- name: Ensure the openshift-nfd namespace exists
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-nfd

- name: Create Subscription
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        labels:
          operators.coreos.com/nfd.openshift-nfd: ''
        name: nfd
        namespace: openshift-nfd
      spec:
        channel: stable
        name: nfd
        installPlanApproval: Automatic
        source: redhat-operators
        sourceNamespace: openshift-marketplace