---

# - name: Create OperatorGroup
#   community.okd.k8s:
#     host: "{{ host }}"
#     api_key: "{{ api_key }}"
#     definition:
#       apiVersion: operators.coreos.com/v1
#       kind: OperatorGroup
#       metadata:
#         name: global-operators
#         namespace: openshift-operators
#       spec: {}

- name: Install Service Mesh Operator
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: servicemeshoperator
        namespace: openshift-operators
      spec:
        channel: stable
        name: servicemeshoperator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Install Serverless Operator
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: serverless-operator
        namespace: openshift-operators
      spec:
        channel: stable
        name: serverless-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Install Authorino Operator
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: authorino-operator
        namespace: openshift-operators
      spec:
        channel: stable
        name: authorino-operator
        source: community-operators
        sourceNamespace: openshift-marketplace

- name: Create namespace for Distributed Tracing
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    name: openshift-distributed-tracing
    api_version: v1
    kind: Namespace
    state: present

- name: Create OperatorGroup
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: openshift-distributed-tracing
        namespace: openshift-distributed-tracing
      spec: {}
    

- name: Install OpenShift Distributed Tracing Platform Operator
  community.okd.k8s:
    host: "{{ host }}"
    api_key: "{{ api_key }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        labels:
          operators.coreos.com/jaeger-product.openshift-distributed-tracing: ''
        name: jaeger-product
        namespace: openshift-distributed-tracing
      spec:
        channel: stable
        name: jaeger-product
        installPlanApproval: Automatic
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        startingCSV: jager-operator.v1.57.0-7

# ONLY NEEDED FOR ROSA v 4.15 and prior
# - name: Create namespace for Elasticsearch
#   community.okd.k8s:
#     host: "{{ host }}"
#     api_key: "{{ api_key }}"
#     name: openshift-logging
#     api_version: v1
#     kind: Namespace
#     state: present

# - name: Install OpenShift Elasticsearch Operator v4.15
#   community.okd.k8s:
#     host: "{{ host }}"
#     api_key: "{{ api_key }}"
#     definition:
#       apiVersion: operators.coreos.com/v1alpha1
#       kind: Subscription
#       metadata:
#         name: elasticsearch-operator
#         namespace: openshift-logging
#       spec:
#         channel: stable-4.15
#         name: elasticsearch-operator
#         source: redhat-operators
#         sourceNamespace: openshift-marketplace