---

- name: Get ROSA cluster api url from terraform outputs
  command: "terraform output -json"
  args:
    chdir: "{{ terraform_dir }}"
  register: tf_output

- name: extract ROSA section
  set_fact:
    rosa_output: "{{ tf_output.stdout | from_json | json_query('rosa') }}"

- name: Convert ROSA output to valid JSON
  set_fact:
    rosa_json: >-
      {{
        rosa_output | to_json | replace('=', ':') | replace('tolist(', '') | replace(')', '') | from_json
      }}

- name: Extract cluster_api_url
  set_fact:
    cluster_api_url: "{{ rosa_json.value.cluster_api_url }}"

- name: Debug cluster_api_url
  debug:
    msg: "Cluster API URL: {{ cluster_api_url }}"

- name: login to ROSA cluster
  community.okd.openshift_auth:
    host: "{{ cluster_api_url }}"
    username: "{{ cluster_admin }}"
    password: "{{ admin_password }}"  
    verify_ssl: false
  register: login

- include_tasks: "{{ item }}"
  with_items:
    - install_other_operators.yaml
    - install_nfd.yaml
    - install_nvidia_gpu_operator.yaml
    - install_rhoai.yaml
  vars: 
    kubeconfig: "{{ login.openshift_auth }}"
    api_key: "{{ login.openshift_auth.api_key }}"
    host: "{{ login.openshift_auth.host }}"